import "oaidl.idl";
import "ocidl.idl";
import "mwcomtypes.idl";

[
    object,
    uuid("F03D82B3-EBFC-4612-8D41-4B25DE0FF4C0"),
    dual,
    helpstring("ITMclass Interface"),
    pointer_default(unique)
]
interface ITMclass : IDispatch
{
    [propget, id(1), helpstring("property MWFlags")]
    HRESULT MWFlags([out, retval] IMWFlags** ppvFlags);
    [propput, id(1), helpstring("property MWFlags")]
    HRESULT MWFlags([in] IMWFlags* pvFlags);
    
    [id(2), helpstring("Method tmair")]
    HRESULT tmair([in] VARIANT freq, [in] VARIANT theta, [in] VARIANT L);

    [id(3), helpstring("Method tmcalc")]
    HRESULT tmcalc([in] VARIANT freq, [in] VARIANT theta,
                   [in] VARIANT TotalThickness);

    [id(4), helpstring("Method tmcheck")]
    HRESULT tmcheck();

    [id(5), helpstring("Method tmelastic")]
    HRESULT tmelastic([in] VARIANT freq, [in] VARIANT theta, [in] VARIANT L,
                      [in] VARIANT BulkDensity, [in] VARIANT FlowRes,
                      [in] VARIANT SFactor, [in] VARIANT h,
                      [in] VARIANT VCL, [in] VARIANT TCL, [in] VARIANT Em,
                      [in] VARIANT LFactor, [in] VARIANT PRatio);

    [id(6), helpstring("Method tmelasticpanel")]
    HRESULT tmelasticpanel([in] VARIANT freq, [in] VARIANT theta,
                           [in] VARIANT L, [in] VARIANT BulkDensity,
                           [in] VARIANT FlowRes, [in] VARIANT SFactor,
                           [in] VARIANT h, [in] VARIANT VCL,
                           [in] VARIANT TCL, [in] VARIANT Em,
                           [in] VARIANT PRatio, [in] VARIANT LFactor,
                           [in] VARIANT hp, [in] VARIANT Densityp,
                           [in] VARIANT Ep, [in] VARIANT PRatiop);

    [id(7), helpstring("Method tmeye")]
    HRESULT tmeye();

    [id(8), helpstring("Method tmimpermemb")]
    HRESULT tmimpermemb([in] VARIANT freq, [in] VARIANT theta,
                        [in] VARIANT L, [in] VARIANT Density);

    [id(9), helpstring("Method tminit")]
    HRESULT tminit();

    [id(10), helpstring("Method tmlimp")]
    HRESULT tmlimp([in] VARIANT freq, [in] VARIANT theta,
                   [in] VARIANT L, [in] VARIANT BulkDensity,
                   [in] VARIANT FlowRes, [in] VARIANT SFactor,
                   [in] VARIANT h, [in] VARIANT VCL, [in] VARIANT TCL);

    [id(11), helpstring("Method tmmul")]
    HRESULT tmmul();

    [id(12), helpstring("Method tmpanel")]
    HRESULT tmpanel([in] VARIANT freq, [in] VARIANT theta,
                    [in] VARIANT L, [in] VARIANT Density,
                    [in] VARIANT Em, [in] VARIANT PRatio);

    [id(13), helpstring("Method tmpanelelastic")]
    HRESULT tmpanelelastic([in] VARIANT freq, [in] VARIANT theta,
                           [in] VARIANT hp, [in] VARIANT Densityp,
                           [in] VARIANT Ep, [in] VARIANT PRatiop,
                           [in] VARIANT L, [in] VARIANT BulkDensity,
                           [in] VARIANT FlowRes, [in] VARIANT SFactor,
                           [in] VARIANT h, [in] VARIANT VCL,
                           [in] VARIANT TCL, [in] VARIANT Em,
                           [in] VARIANT PRatio, [in] VARIANT LFactor);

    [id(14), helpstring("Method tmpanelelasticpanel")]
    HRESULT tmpanelelasticpanel([in] VARIANT freq, [in] VARIANT theta,
                                [in] VARIANT hp1, [in] VARIANT Densityp1,
                                [in] VARIANT Ep1, [in] VARIANT PRatiop1,
                                [in] VARIANT L, [in] VARIANT BulkDensity,
                                [in] VARIANT FlowRes, [in] VARIANT SFactor,
                                [in] VARIANT h, [in] VARIANT VCL,
                                [in] VARIANT TCL, [in] VARIANT Em,
                                [in] VARIANT PRatio, [in] VARIANT LFactor,
                                [in] VARIANT hp2, [in] VARIANT Densityp2,
                                [in] VARIANT Ep2, [in] VARIANT PRatiop2);

    [id(15), helpstring("Method tmpermemb")]
    HRESULT tmpermemb([in] VARIANT freq, [in] VARIANT theta, [in] VARIANT L,
                      [in] VARIANT Density, [in] VARIANT FlowRes);

    [id(16), helpstring("Method tmrigid")]
    HRESULT tmrigid([in] VARIANT freq, [in] VARIANT theta,
                    [in] VARIANT L, [in] VARIANT BulkDensity,
                    [in] VARIANT FlowRes, [in] VARIANT SFactor,
                    [in] VARIANT h, [in] VARIANT VCL, [in] VARIANT TCL);

        [propget, id(17), helpstring("property TM")]
        HRESULT TM([out, retval] VARIANT* TM);
        [propput, id(17), helpstring("property TM")]
        HRESULT TM([in] VARIANT TM);
    
        [propget, id(18), helpstring("property c")]
        HRESULT c([out, retval] VARIANT* c);
        [propput, id(18), helpstring("property c")]
        HRESULT c([in] VARIANT c);
    
        [propget, id(19), helpstring("property Densityo")]
        HRESULT Densityo([out, retval] VARIANT* Densityo);
        [propput, id(19), helpstring("property Densityo")]
        HRESULT Densityo([in] VARIANT Densityo);
    
        [propget, id(20), helpstring("property HeatRatio")]
        HRESULT HeatRatio([out, retval] VARIANT* HeatRatio);
        [propput, id(20), helpstring("property HeatRatio")]
        HRESULT HeatRatio([in] VARIANT HeatRatio);
    
        [propget, id(21), helpstring("property Npr")]
        HRESULT Npr([out, retval] VARIANT* Npr);
        [propput, id(21), helpstring("property Npr")]
        HRESULT Npr([in] VARIANT Npr);
    
        [propget, id(22), helpstring("property ItaAir")]
        HRESULT ItaAir([out, retval] VARIANT* ItaAir);
        [propput, id(22), helpstring("property ItaAir")]
        HRESULT ItaAir([in] VARIANT ItaAir);
    
        [propget, id(23), helpstring("property P0")]
        HRESULT P0([out, retval] VARIANT* P0);
        [propput, id(23), helpstring("property P0")]
        HRESULT P0([in] VARIANT P0);
    
        [propget, id(24), helpstring("property Result")]
        HRESULT Result([out, retval] VARIANT* Result);
        [propput, id(24), helpstring("property Result")]
        HRESULT Result([in] VARIANT Result);
    
        [propget, id(25), helpstring("property Rigid")]
        HRESULT Rigid([out, retval] VARIANT* Rigid);
        [propput, id(25), helpstring("property Rigid")]
        HRESULT Rigid([in] VARIANT Rigid);
    
        [propget, id(26), helpstring("property Anechoic")]
        HRESULT Anechoic([out, retval] VARIANT* Anechoic);
        [propput, id(26), helpstring("property Anechoic")]
        HRESULT Anechoic([in] VARIANT Anechoic);
    
        [propget, id(27), helpstring("property TL")]
        HRESULT TL([out, retval] VARIANT* TL);
        [propput, id(27), helpstring("property TL")]
        HRESULT TL([in] VARIANT TL);
    
        [propget, id(28), helpstring("property TM11")]
        HRESULT TM11([out, retval] VARIANT* TM11);
        [propput, id(28), helpstring("property TM11")]
        HRESULT TM11([in] VARIANT TM11);
    
        [propget, id(29), helpstring("property TM12")]
        HRESULT TM12([out, retval] VARIANT* TM12);
        [propput, id(29), helpstring("property TM12")]
        HRESULT TM12([in] VARIANT TM12);
    
        [propget, id(30), helpstring("property TM21")]
        HRESULT TM21([out, retval] VARIANT* TM21);
        [propput, id(30), helpstring("property TM21")]
        HRESULT TM21([in] VARIANT TM21);
    
        [propget, id(31), helpstring("property TM22")]
        HRESULT TM22([out, retval] VARIANT* TM22);
        [propput, id(31), helpstring("property TM22")]
        HRESULT TM22([in] VARIANT TM22);
    
        [propget, id(32), helpstring("property Result11")]
        HRESULT Result11([out, retval] VARIANT* Result11);
        [propput, id(32), helpstring("property Result11")]
        HRESULT Result11([in] VARIANT Result11);
    
        [propget, id(33), helpstring("property Result12")]
        HRESULT Result12([out, retval] VARIANT* Result12);
        [propput, id(33), helpstring("property Result12")]
        HRESULT Result12([in] VARIANT Result12);
    
        [propget, id(34), helpstring("property Result21")]
        HRESULT Result21([out, retval] VARIANT* Result21);
        [propput, id(34), helpstring("property Result21")]
        HRESULT Result21([in] VARIANT Result21);
    
        [propget, id(35), helpstring("property Result22")]
        HRESULT Result22([out, retval] VARIANT* Result22);
        [propput, id(35), helpstring("property Result22")]
        HRESULT Result22([in] VARIANT Result22);
    };
[
    uuid("40E7FF4F-65EE-443D-90B4-17B2C6683DA2"),
    version(1.0),
    helpstring("TM 1.0 Type Library")
]
library TM
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");
    importlib("mwcomutil.tlb");
    
    [
        uuid("21B24D28-FD47-4A40-84DB-A3C0729DA73A"),
        helpstring("TMclass Class")
    ]
    coclass TMclass
    {
        [default] interface ITMclass;
    };
};
